version: "3"

services:
  app:
    environment:
      REGISTRY_URL: ${REGISTRY_URL:-docker.io}
      REGISTRY_USER: ${REGISTRY_USER:?err}
      REGISTRY_TOKEN: ${REGISTRY_TOKEN:?err}
      DOCKER_LOGIN: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONTAINERS_MOUNT_PATH:?err}:/containers